apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  type: NodePort
  ports:
  - port: {{ .Values.flaskApp.service.port }}
    targetPort: 5000
    nodePort: 30000
  selector:
    app: flask-app
